### ISSUE TITLE
TODO: unset API/UID data if API calls return 404

### ISSUE THREAD

**Issue by micschk** [restruct/silverstripe-cfstreamvideo#3]
Currently 404 errors are set to be ignored (to prevent halting execution on errors, see: #2 ).
We should probably add handling to update the local data to reflect situations in which the video has been manually deleted from the API (eg in `refreshDataFromApi()`).

**Comment by lekoala** [comment]
fixed in https://github.com/restruct/silverstripe-cfstreamvideo/commit/036844b522b7e3f89fd8dc0dc6dd59f9632de7a8

i added a warning message if there was no write on the record
