### ISSUE TITLE
When using signed urls, ThumbnailURL & poster option of player needs to use signed url as well

### ISSUE THREAD

**Issue by micschk** [restruct/silverstripe-cfstreamvideo#4]
See: https://developers.cloudflare.com/stream/viewing-videos/displaying-thumbnails#use-case-1-generating-a-thumbnail-on-the-fly

> Using the poster query parameter in the embed URL, you can set a thumbnail to any time in your video. If signed URLs are required, you must use signed URL instead of video IDs.

<img width="706" alt="Screenshot 2021-07-03 at 08 42 35" src="https://user-images.githubusercontent.com/1005986/124345680-ac991880-dbda-11eb-8f5b-4fa976ca3d2c.png">

**Comment by lekoala** [comment]
fixed in https://github.com/restruct/silverstripe-cfstreamvideo/commit/53fa9720d82e96666f0d39456b292d2388156bf4

we cannot use ThumbnailURL provided by the api, but getPosterImageUrlFromApi method instead
