### ISSUE TITLE
Sync Name to CF as well

### ISSUE THREAD

**Issue by micschk** [restruct/silverstripe-cfstreamvideo#6]
The name of a video should be synced back to CF via the API

**Comment by lekoala** [comment]
Isn't that what  does ?

https://github.com/restruct/silverstripe-cfstreamvideo/blob/30cf45a69c33cdd3f77c41e203ac2d50e7837243/src/Model/StreamVideoObject.php#L419

**Comment by micschk** [comment]
> Isn't that what does ?

Yes, added this morning :-)
