### ISSUE TITLE
Request: OEmbed functionality

### ISSUE THREAD

**Issue by micschk** [restruct/silverstripe-cfstreamvideo#7]
@lekoala If you're interested, it'd be nice if we could add [OEmbed functionality](/restruct/silverstripe-cfstreamvideo/blob/main/README.md#oembed)

**Comment by lekoala** [comment]
@micschk just pushed some basic support for this

**Comment by micschk** [comment]
@lekoala thanks for this! 
It did seem to need some more work as it wasn't fully functional yet when I tested it, but it was a good start!

Finished with bf07d7ac6702d747f8d8dcc115944b7d2e4d7091
